# set server to use the conventional port that the config server is expected to run on
server:
  port: 8888

# Point the config server at the git repo containing the configuration settings

spring:
  kafka:
    bootstrap-servers: localhost:9092
  cloud:
    config:
      server:
        git:
          uri: https://github.com/ramya-sks/spring-cloud-config-basics-repo.git
